# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: gcp.solutions/v1
kind: BrokerAppConfig
metadata:
  name: brutal-doom
spec:
  version: 1.0.0
  name: brutal-doom
  displayName: Brutal Doom
  description: Freedoom with Brutal Doom MOD
  icon: https://i.ibb.co/HhMnV16/brutal-doom-icon.png
  bundle:
    configMapRef:
      name: webrtc-gpu-streaming-manifests-1.4.0
  serviceName: vdi
  defaultRepo: gcr.io/${PROJECT_ID}/vdi-gzdoom-brutal-doom
  defaultTag: "latest"
  images:
    xserver:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-xserver
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-xserver
      newTag: latest
    desktop:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-desktop
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-desktop
      newTag: latest
    pulseaudio:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-pulseaudio
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-pulseaudio
      newTag: latest
    gst-webrtc-app:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-gst-webrtc-app
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-gst-webrtc-app
      newTag: latest
    signaling:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-signaling
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-signaling
      newTag: latest
    gst-web:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-gst-web
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-gst-web
      newTag: latest
    xpra:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-xpra
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-xpra
      newTag: latest
    watchdog:
      oldRepo: gcr.io/cloud-solutions-images/webrtc-gpu-streaming-watchdog
      newRepo: gcr.io/${PROJECT_ID}/webrtc-gpu-streaming-watchdog
      newTag: latest
  userParams:
    - name: enableAudio
      displayName: "Audio"
      type: bool
      default: "true"
    - name: enablePersistence
      displayName: "Persistent Home"
      type: bool
      default: "false"
    - name: enableXpra
      displayName: "Use Xpra"
      type: bool
      default: "false"
    - name: enableVirtualMouse
      displayName: "Virtual Mouse Device"
      type: bool
      default: "false"
  appParams:
    - name: idleShutdownTimeout
      default: "600" # seconds
  appEnv:
    - name: XPRA_ENTRYPOINT
      value: "blender"
  defaultTier: gpu
  nodeTiers:
    - name: gpu
      nodeLabel: gpu-cos
      resources:
        requests:
          cpu: 500m
    - name: standard
      nodeLabel: tier1
      resources:
        requests:
          cpu: 500m
