# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s

substitutions:
  _USE_CACHE: "true"
  _IMAGE_PREFIX: vdi
  _IMAGE_TAG: latest

tags:
  - egress-proxy-images

###
# Images to be pushed
###
images: [
    # squid
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid:latest',
]

steps:
###
# Squid proxy image
###
- name: 'gcr.io/cloud-builders/docker'
  id: squid-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: squid
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid:latest',
            'squid'
        ]
  waitFor:
    - squid-pull
- name: 'gcr.io/cloud-builders/docker'
  id: squid-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-squid:latest',
        ]
  waitFor:
    - squid
