apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: vdi-vm-default-token-creator
spec:
  member: serviceAccount:vdi-vm-default@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/iam.serviceAccountTokenCreator
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: projects/${PROJECT_ID}/serviceAccounts/vdi-vm-default@${PROJECT_ID}.iam.gserviceaccount.com
