# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 300s
substitutions:
  _ACTION: apply
  _NAME: broker
  _REGION: us-west1

steps:
  ###
  # Generate SSH key and save to Secret Manager
  ###
  - name: gcr.io/cloud-builders/gcloud
    id: vdi-vm-controller-ssh-key
    entrypoint: bash
    args:
      - -exc
      - |
        (gcloud secrets versions access 1 --secret vdi-vm-controller-ssh-key >/dev/null) && exit 0
        ssh-keygen -f vdi-vm-controller.key -t rsa -N ''
        gcloud secrets create vdi-vm-controller-ssh-key \
              --replication-policy=automatic \
              --data-file vdi-vm-controller.key
  ###
  # Deploy manifests to cluster.
  ###
  - name: "gcr.io/cloud-builders/kubectl"
    id: deploy-manifests
    entrypoint: bash
    args:
      - -exc
      - |
        kubectl kustomize . | sed \
          -e 's/$${PROJECT_ID}/${PROJECT_ID}/g' \
          -e 's/$${REGION}/'${_REGION}'/g' \
          | /builder/kubectl.bash ${_ACTION} -f -
    env:
      - "CLOUDSDK_CORE_PROJECT=${PROJECT_ID}"
      - "CLOUDSDK_COMPUTE_REGION=${_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_NAME}-${_REGION}"

  - name: "gcr.io/cloud-builders/kubectl"
    id: wait-for-cnrm
    entrypoint: bash
    args:
      - -exc
      - |
        for t in iamserviceaccount iampolicymember computenetwork computesubnetwork computefirewall; do
          kubectl wait $t -l app=vdi-vm --for=condition=Ready --timeout=180s -n pod-broker-system
        done
    env:
      - "CLOUDSDK_CORE_PROJECT=${PROJECT_ID}"
      - "CLOUDSDK_COMPUTE_REGION=${_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_NAME}-${_REGION}"
